### ISSUE TITLE
timezone has no data for null

### ISSUE THREAD

**Issue by mfrederickson** [concerto/concerto-frontend#45]
You're probably already aware of this...
![image](https://cloud.githubusercontent.com/assets/473165/9802362/17f66028-57c6-11e5-9552-1899b3083a74.png)

**Comment by gbprz** [comment]
Hmm, which time zone were you trying to set? I pushed some code to core Concerto last night to include  the time zone string in the screen's setup.js. If those changes weren't pulled in, it might be giving you that error. Otherwise, it might be an issue with the time zone mapping from Rails strings to the momentjs  available time zones.

**Comment by gbprz** [comment]
After talking it through with @augustf, he pointed out that the screen might not even have a time zone set after the db migration.that adds this column. It seems like the time is just displaying your local time without any time zone adjustments as a result. The error message is unpleasant though, so I can add a check for the absence of any time zone and just get the local time instead.

**Comment by gbprz** [comment]
This should now be fixed as of 97512be306acc4f8a18d1d57481c5c3c50499c7e and ada6c403109021a892b971341e6c5b3154e8fd4c
